---
name: API
base_url: "https://pokeapi.co/api/v2"
endpoints:
  pokemon: "/pokemon"
  pokemon_species: "/pokemon-species"
  ability: "/ability"
  type: "/type"
  move: "/move"
  item: "/item"
  location: "/location"
  generation: "/generation"
...